### PR TITLE
Upgrade to Django 2.2 LTS

### PR DESCRIPTION
**Pull request by webyneter**
* [x] upgrade to Django 2.2 LTS 
* [x] upgrade other dependencies to latest versions
* [x] update readmes
* [x] clean up pre-Django 2 artifacts 
* [x] make sure other dependencies are compatible with Django 2.2
* [x] support per-project requirements
* [x] test everything out with a freshly-generated project in Docker environment

## Steps to validate

In the directory for your future project do:

```
cookiecutter ../cookiecutter-django --overwrite-if-exists --no-input project_name=test_django22 debug=y use_docker=y use_pycharm=y rest_framework_json_api=y dynamic_rest=y
cd ./test_django22
docker-compose -f local.yml build
docker-compose -f local.yml up -d
# Navigate 0.0.0.0:8000
```

### CODE REVIEW

**Comment by webyneter** [comment]
I've tested the generated project in runtime: admin & auth flow work and so do database operations. django-debug--toolbar & django-extensions are functioning properly, too.

**Comment by simkimsia** [comment]
@webyneter 

This is more to do with the dynamic rest I was discussing with you previously.

i used the following because dynamic rest on pypi is 1.8 and i wanted to use 1.9

`-e git+https://github.com/AltSchool/dynamic-rest.git@v1.9.3#egg=dynamic-rest`

what happens is that during `docker-compose -f local.yml build` I get this

```
Cloning https://github.com/AltSchool/dynamic-rest.git (to revision v1.9.3) to /src/dynamic-rest
  Error [Errno 2] No such file or directory: 'git': 'git' while executing command git clone -q https://github.com/AltSchool/dynamic-rest.git /src/dynamic-rest
Cannot find command 'git' - do you have 'git' installed and in your PATH?
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'django' failed to build: The command '/bin/sh -c pip install -r /requirements/local.txt' returned a non-zero code: 1
```

i think what i did previously was that I somehow install git via

```
RUN apk update \
  # additional libraries -- add here
  # add git because need to use for requirements.txt
  && apk add git \
```

So should I make that change as well?

Like to hear your thoughts.

**Comment by webyneter** [comment]
@simkimsia yes, indeed, latest version of dynamic-rest is yet to be released on PyPI. For now the easiest way to install it is through git egg mechanism as you mentioned, the #2 PR addresses it.

**Comment by webyneter** [comment]
@simkimsia, also, regarding support for per-project requirements, how about I introduce the `project.base.txt`, `project.local.txt`, and `project.production.txt` files referncing them from within `base.txt`, `local.txt`, and `production.txt`, respectively, encouraging derivative projects' owners to declare their dependencies inside these three?

**Comment by simkimsia** [comment]
I cannot tell if it’s a good idea. I Guess let’s give it a shot.

Sorry for late reply as I am traveling for work.

I’ll be more responsive tomorrow.

**Pull request merged**
